# Generated by Django 3.2.4 on 2021-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20210622_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='slack_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
