# Generated by Django 3.2.4 on 2021-06-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20210629_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='gitlab_id',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='username',
        ),
    ]
