# Generated by Django 3.2.4 on 2021-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_auto_20210629_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='participants',
            field=models.ManyToManyField(null=True, to='discussions.Developer'),
        ),
    ]
