# Generated by Django 3.2.4 on 2021-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_alter_discussion_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='participants',
            field=models.ManyToManyField(to='discussions.Developer'),
        ),
    ]
