# Generated by Django 3.2.4 on 2021-06-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_alter_discussion_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='line',
        ),
    ]
