# Generated by Django 3.2.4 on 2021-06-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('slack_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('default_branch', models.CharField(max_length=100)),
                ('web_url', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='review.developer')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_id', models.CharField(max_length=50)),
                ('short_id', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('web_url', models.SlugField(max_length=200)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='review.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='review.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('line', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.developer')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.commit')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.discussion')),
            ],
        ),
    ]
